# SwiftLint Configuration for AuvasaKit
# Modern, strict rules for high-quality Swift code

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Sources/AuvasaKit/Generated # Protobuf generated code
  - Tests/AuvasaKitTests/Fixtures
  - Pods
  - Carthage
  - vendor

# Paths to include (optional, but explicit is good)
included:
  - Sources
  - Tests

# Analyzer rules (requires compilation, more thorough)
analyzer_rules:
  - unused_import
  - unused_declaration

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules (explicitly disabled for clarity)
disabled_rules:
  - todo # Allow TODO comments
  - multiple_closures_with_trailing_closure # Sometimes necessary
  - file_header # Can be added later when project matures
  - file_name # Allow generic file names like Types.swift
  - function_default_parameter_at_end # Sometimes order matters for API design
  - pattern_matching_keywords # Conflicts with SwiftFormat preferences
  - conditional_returns_on_newline # Too strict for simple returns
  - opening_brace # Conflicts with SwiftFormat multiline guard formatting

# Custom rule configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL
    - T
    - U
    - V

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - at
    - to
    - db
    - url
    - a
    - b
    - c  # Mathematical variables in formulas

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2

# File header configuration (disabled for now, can be enabled later)
# file_header:
#   required_pattern: |
#                     \/\/
#                     \/\/ .*?\.swift
#                     \/\/ AuvasaKit
#                     \/\/

# Naming conventions
generic_type_name:
  min_length: 1
  max_length: 20

# Force cast and unwrapping (strict)
force_cast: warning
force_try: warning
force_unwrapping: warning

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  # Avoid print statements (use Logger instead)
  no_print:
    name: "No print statements"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use Logger instead of print for production code"
    severity: warning

  # Disabled - too strict for modern Swift
  # explicit_self_in_closure:
  #   name: "Explicit self in closures"
  #   regex: "\\{[^}]*(?<!self\\.)(?:self|super)\\.[a-zA-Z_]+"
  #   message: "Use explicit self in closures for clarity"
  #   severity: warning

  # No force unwrapping in production code
  no_force_unwrapping_in_tests:
    name: "No force unwrapping except in tests"
    regex: "![\\s]*\\.\\w+\\("
    match_kinds:
      - identifier
    message: "Avoid force unwrapping, use optional binding or guard"
    severity: warning

# Reporter
reporter: "xcode"
